"use strict";
var etg = require("./etg");
var data = {
	accelerationspell: "Replaces target creature's skills with \"Acceleration: gain +2|-1 per turn\"",
	adrenaline: "Target creature attacks multiple times per turn. Weaker creatures gain more attacks",
	aflatoxin: "Apply 2 poison to target. When target dies, it turns into a malignant cell",
	aggroskele: "Summon a 2|2 Skeleton. All own skeletons attack target creature",
	antimatter: "Invert strength of target",
	atk2hp: "Target's largeness becomes equal to its strength",
	bblood: "Target creature gains 0|20 & is delayed 6 turns",
	beguile: "Steal target creature until next turn",
	blackhole: "Absorb 3 quanta per element from target player. Heal 1 life per absorbed quantum",
	bless: "Target gains 3|3",
	bolsterintodeck: "Push 3 copies of target creature onto own deck. Cannot ricochet",
	bravery: "foe draws 2 cards, you draw an equal amount of cards",
	butterfly: "Target something smaller than, or weaker than, 3. Replace target's skills with \"3:1 Destroy: destroy target permanent\"",
	chimera: "Combine all your creatures to form a Chimera with momentum & gravity pull",
	corpseexplosion: ["Sacrifice a creature to deal 1 damage to all creatures. Poisonous sacrifices poison foe",
		"Sacrifice a creature to deal 1 damage to all enemy creatures. Poisonous sacrifices poison foe"],
	cpower:"Target gains 1 to 5 strength. Target gains 1 to 5 largeness",
	cseed:"A random effect is inflicted to target creature",
	deckblast: "Damage foe per card in deck. Discard deck",
	destroy: "Destroy target permanent",
	destroycard: "Discard target card",
	divinity: "Add 24 to maximum health & heal 16",
	draft: "Target airborne creature loses airborne status, or vice versa. Produce 2:9",
	drainlife: "Drains 2 life from target. Drain additional life per 5:11 owned",
	dryspell: "Deal 1 damage to all creatures. Gain 1:7 per damage dealt. Removes cloak",
	earthquake: "Destroy up to 3 stacked permanents",
	enchant: "Target permanent becomes immaterial",
	envenom: "Target weapon gains Venom: apply poison on hit",
	firebolt: "Deals 3 damage to target. Increment damage per 4:6 owned. Thaws target",
	flatline: "No quanta is produced in foe's next turn",
	flyingweapon: "Target weapon becomes a flying creature",
	fractal: "Generate 6 copies of target creature's card. Consumes remaining 1:12. Generate another copy per 2:12 consumed",
	freeze: ["Freeze target for 3 turns. Being frozen disables attacking & per turn skills",
		"Freeze target for 4 turns. Being frozen disables attacking & per turn skills"],
	give: ["Give own target to foe. Heal self 10",
		"Give own target to foe. Heal self 5"],
	gpullspell: "Target creature intercepts attacks directed to its owner",
	heal: "Heal target 20",
	holylight: "Heal target 10. Nocturnal targets are damaged instead",
	icebolt: "Deal 2 damage to target. Increment damage per 5:7 owned. May freeze target",
	immolate: "Sacrifice a creature to produce 6:6 & 1 quanta of each other element",
	improve: "Mutate target creature",
	innovation: "Discard target card, owner draws three cards",
	integrity: "Combine all shards in hand to form a Shard Golem",
	lightning: "Deal 5 damage to target",
	liquid: "Target creature is poisoned & skills replaced with \"Vampirism: damage dealt is returned as healing\"",
	livingweapon: "Target creature becomes equipped as a weapon. Heal target's owner for health of target",
	luciferin: "All your creatures without skills produce 1:8. Heal self 10",
	metamorph: "Change mark to target's element. Produce 2 quanta of that element",
	midas: "Target permanent becomes a Golden Relic with 2:0 Vend: sacrifice Golden Relic & draw a card",
	miracle: "Heal self to one below maximum life. Consumes remaining 1:8",
	mitosisspell: "Non-weapon creature gains 0|1 & active \"Mitosis: Summon a daughter creature\" costing target's card's cost",
	momentum: "Target ignores shield effects & gains 1|1",
	mutation:"Mutate target creature into an abomination, or maybe something more. Slight chance of death",
	neuroify: "Gives foe neurotoxin status if they are already poisoned",
	nightmare: "Fill foe's hand with copies of target creature's card. Drain 2 life per added card",
	nova: "Produce 1 quanta of each element. Increment singularity danger by 2. Summon singularity if danger exceeds 5",
	nova2: "Produce 2 quanta of each element. Increment singularity danger by 3. Summon singularity if danger exceeds 5",
	nymph: "Turn target pillar into a Nymph of same element",
	overdrivespell: "Replaces target creature's skills with \"Overdrive: gain +3|-1 per turn\"",
	pacify: "Reduce target's attack to 0",
	pandemonium2: "Random effects are inflicted to target player's creatures. Removes cloak",
	pandemonium: "Random effects are inflicted to all creatures. Removes cloak",
	parallel: "Duplicate target creature",
	plague: "Poison target player's creatures. Removes cloak",
	platearmor: ["Target gains 0|4", "Target gains 0|6"],
	"poison 1":{
		hit:"Apply 1 poison on hit",
		cast:"Apply 1 poison to foe"
	},
	"poison 2":{
		hit:"Apply 2 poison on hit",
		cast:"Apply 2 poison to foe"
	},
	"poison 3":{
		hit:"Apply 3 poison on hit",
		cast:"Apply 3 poison to foe"
	},
	powerdrain: "Halve target creature's strength & largeness. Strength & largeness lost is added to one of your creatures",
	precognition: "Reveal foe's hand until end of their turn. Draw a card",
	protectall: "Bubble each of own creatures & permanents. Bubbles protect from next targeting or spell damage",
	purify: "Replace poison statuses with 2 purify. Removes sacrifice",
	quantagift: "Gain 2:7 & 2 quanta of mark. Produce only 3:7 if mark is 1:7",
	quint: "Target creature becomes immaterial. Thaws",
	rage: ["Target creature gains +5|-5. Thaws",
		"Target creature gains +6|-6. Thaws"],
	readiness: "Target creature's active becomes costless. Skill can be reactivated",
	regeneratespell: "Replace non-stacking target's skills with \"Regenerate: Heal owner 5 each turn\"",
	regrade: "Inverse upgraded status of target card or creature. Produce 1 quanta of that element",
	rewind: "Remove target creature to top of owner's deck",
	scatterhand: "Target player shuffles their hand, & draws however many cards previously had",
	serendipity:["Generate 3 random non-pillar cards in hand. One will be 1:1",
		"Generate 3 random non-pillar upgraded cards in hand. One will be 1:1"],
	silence: "foe cannot play cards during their next turn, or target creature gains summoning sickness",
	sinkhole: ["Target creature is burrowed. Replace creature's skills with 0: unburrow",
		"Target creature is burrowed. Replace creature's skills with 1:4: unburrow"],
	skyblitz: "Double next attack of all own airborne creatures. Consumes remaining 1:9",
	sosa: ["Sacrifice 48% of maximum health & consume all non 1:2 to invert damage for 2 turns",
		"Sacrifice 40% of maximum health & consume all non 1:2 to invert damage for 2 turns"],
	sskin: "Increment maximum life per 1:4 owned. Heal same",
	steal: "Steal target permanent",
	"storm 2": "Deals 2 damage to target player's creatures. Removes cloak",
	"storm 3": "Deals 3 damage to target player's creatures. Removes cloak",
	swave: "Deals 4 damage to target. Instantly kill creature or destroy weapon if frozen",
	tempering: ["Target weapon deals an additional 3 damage per turn. Thaws",
		"Target weapon deals an additional 5 damage per turn. Thaws"],
	throwrock: ["Deal 3 spell damage to target creature, then shuffle Throw Rock into target's deck",
		"Deal 4 spell damage to target creature, then shuffle Throw Rock into target's deck"],
	tidalhealing: "Own aquatic creatures without Regen gain Regen",
	tornado: ["Randomly reshuffle 2 of foe's permanents & one of own into either deck",
		"Randomly reshuffle 2 of foe's permanents into either deck"],
	unsummon: "Return target creature to owner's hand",
	wisdom: "Target gains 3|0. May target immaterial, granting psionic",
	yoink: "Steal target card",
};
module.exports = function(c, event){
	if (c instanceof etg.Card){
		var entry = data[c.active.activename[0]];
		if (entry.cast) entry = entry.cast;
		return typeof entry === "string" ? entry : entry[c.upped?1:0];
	}else{
		//TODO
	}
}